M48
; DRILL file {KiCad 9.0.7} date 2026-09-27T10:00:25+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-27T10:00:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X138.505Y-115.646
T2
X158.505Y-115.646
M30
